try{func()}catch(e){log(e)}