while(_){try{if(a<1)throw"err"}catch(e){continue}call()}